# The URL the site will be built for
base_url = "https://wydnabooks.com"
generate_feed = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [
    {name = "tags", feed = true},
    {name = "faggot", feed = true},
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
sort_by = "date"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true



[extra]
# Put all your custom variables here
